import { FileBarChart2, Download, Plus, Clock } from 'lucide-react';
import { Card, CardHeader, Badge, Table, Button, PageHeader } from '@/components/ui';
import type { TableColumn } from '@/components/ui';
import type { Report } from '@/types';
import { formatDateTime } from '@/utils/format';

const MOCK_REPORTS: Report[] = [
  {
    id: '1',
    title: 'Monthly Safety Report – June 2026',
    type: 'Monthly',
    generatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    generatedBy: 'System',
    status: 'ready',
    downloadUrl: '#',
  },
  {
    id: '2',
    title: 'Incident Analysis Q2 2026',
    type: 'Quarterly',
    generatedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    generatedBy: 'Admin',
    status: 'ready',
    downloadUrl: '#',
  },
  {
    id: '3',
    title: 'Equipment Inspection – Zone A',
    type: 'Custom',
    generatedAt: new Date().toISOString(),
    generatedBy: 'Supervisor',
    status: 'pending',
  },
];

const columns: TableColumn<Report>[] = [
  {
    key: 'title',
    header: 'Report',
    accessor: 'title',
    render: (v, _row) => (
      <div className="flex items-center gap-2">
        <FileBarChart2 className="w-4 h-4 text-[var(--color-text-muted)] flex-shrink-0" />
        <span className="font-medium text-[var(--color-text-primary)]">{v as string}</span>
      </div>
    ),
  },
  { key: 'type',        header: 'Type',         accessor: 'type' },
  {
    key: 'generatedAt',
    header: 'Generated',
    accessor: 'generatedAt',
    render: (v) => (
      <span className="text-xs text-[var(--color-text-muted)] flex items-center gap-1">
        <Clock className="w-3 h-3" />
        {formatDateTime(v as string)}
      </span>
    ),
  },
  { key: 'generatedBy', header: 'Generated By', accessor: 'generatedBy' },
  {
    key: 'status',
    header: 'Status',
    accessor: 'status',
    render: (v) => (
      <Badge
        variant={v === 'ready' ? 'success' : v === 'pending' ? 'warning' : 'danger'}
        size="sm"
        dot
      >
        {(v as string).charAt(0).toUpperCase() + (v as string).slice(1)}
      </Badge>
    ),
  },
  {
    key: 'actions',
    header: '',
    accessor: 'downloadUrl',
    align: 'right',
    render: (v) =>
      v ? (
        <Button
          variant="ghost"
          size="xs"
          leftIcon={<Download className="w-3.5 h-3.5" />}
          onClick={(e) => e.stopPropagation()}
        >
          Download
        </Button>
      ) : null,
  },
];

export function ReportsPage() {
  return (
    <div className="page-container">
      <PageHeader
        title="Reports"
        description="Generate and download safety compliance reports."
        actions={
          <Button leftIcon={<Plus className="w-4 h-4" />}>
            Generate Report
          </Button>
        }
        border={false}
        className="px-0 pt-0"
      />

      <Card padding="none">
        <CardHeader title="Report History" className="px-6 pt-5 pb-0" />
        <div className="p-4">
          <Table<Report>
            columns={columns}
            data={MOCK_REPORTS}
            keyExtractor={(r) => r.id}
            caption="Report history"
          />
        </div>
      </Card>
    </div>
  );
}
