import { useState } from 'react';
import { FileBarChart2, Clock, Search, Filter } from 'lucide-react';
import { Card, CardHeader, Badge, Table, Button, PageHeader, Input, Alert } from '@/components/ui';
import type { TableColumn } from '@/components/ui';
import type { Report } from '@/types';
import { formatDateTime } from '@/utils/format';
import { useReports } from '@/features/reports/hooks/useReports';

const columns: TableColumn<Report>[] = [
  {
    key: 'title',
    header: 'Report',
    accessor: 'title',
    render: (v, _row) => (
      <div className="flex items-center gap-2">
        <FileBarChart2 className="w-4 h-4 text-[var(--sf-text-tertiary)] flex-shrink-0" />
        <span className="font-medium text-[var(--sf-text-primary)]">{v as string}</span>
      </div>
    ),
  },
  { key: 'type',        header: 'Type',         accessor: 'type' },
  {
    key: 'generatedAt',
    header: 'Generated',
    accessor: 'generatedAt',
    render: (v) => (
      <span className="text-xs text-[var(--sf-text-tertiary)] flex items-center gap-1">
        <Clock className="w-3 h-3" />
        {formatDateTime(v as string)}
      </span>
    ),
  },
  { key: 'generatedBy', header: 'Generated By', accessor: 'generatedBy' },
  {
    key: 'status',
    header: 'Status',
    accessor: 'status',
    render: (v) => (
      <Badge
        variant={v === 'ready' ? 'success' : v === 'pending' ? 'warning' : 'danger'}
        size="sm"
        dot
      >
        {(v as string).charAt(0).toUpperCase() + (v as string).slice(1)}
      </Badge>
    ),
  },
];

export function ReportsPage() {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const limit = 10;
  const skip = (page - 1) * limit;

  const { reports, total, loading, error } = useReports({ limit, skip, search });

  const totalPages = Math.ceil(total / limit) || 1;

  return (
    <div className="page-container">
      <PageHeader
        title="Reports"
        description="View and track safety compliance, risks, and incident reports."
        border={false}
        className="px-0 pt-0"
      />

      <Card padding="none">
        <CardHeader 
          title="Report History" 
          className="px-6 pt-5 pb-4 border-b border-[var(--sf-border-default)]"
          action={
            <div className="flex items-center gap-2">
              <div className="relative">
                <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-[var(--sf-text-tertiary)]" />
                <Input
                  placeholder="Search reports..."
                  value={search}
                  onChange={(e) => { setSearch(e.target.value); setPage(1); }}
                  className="pl-9 w-64"
                />
              </div>
              <Button variant="outline" leftIcon={<Filter className="w-4 h-4" />}>
                Filter
              </Button>
            </div>
          }
        />
        <div className="p-4">
          {error && (
            <Alert variant="danger" title="Failed to load reports" className="mb-4">
              {error}
            </Alert>
          )}

          <Table<Report>
            columns={columns}
            data={reports}
            keyExtractor={(r) => r.id}
            caption="Report history"
            loading={loading}
            emptyMessage={search ? "No reports match your search criteria." : "No reports have been generated yet."}
          />
          
          {total > 0 && (
            <div className="flex items-center justify-between mt-4 px-2">
              <span className="text-sm text-[var(--sf-text-tertiary)]">
                Showing {skip + 1} to {Math.min(skip + limit, total)} of {total} reports
              </span>
              <div className="flex gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  disabled={page === 1 || loading}
                  onClick={() => setPage(p => p - 1)}
                >
                  Previous
                </Button>
                <Button 
                  variant="outline" 
                  size="sm" 
                  disabled={page === totalPages || loading}
                  onClick={() => setPage(p => p + 1)}
                >
                  Next
                </Button>
              </div>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
}
