"""Initial schema

Revision ID: fb7da06618a2
Revises: 
Create Date: 2026-07-07 22:17:24.680530
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7da06618a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('alert_type', sa.Enum('WARNING', 'CRITICAL', name='alerttype', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=50), nullable=False, comment='Source system that generated the alert'),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus', native_enum=False, length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_alert_type', 'alerts', ['alert_type'], unique=False)
    op.create_index('ix_alerts_generated_at', 'alerts', ['generated_at'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_zone', 'alerts', ['zone'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel', native_enum=False, length=20), nullable=False),
    sa.Column('incident_type', sa.Enum('GAS_LEAK', 'FIRE', 'EXPLOSION', 'PPE_VIOLATION', name='incidenttype', native_enum=False, length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_incident_type', 'incidents', ['incident_type'], unique=False)
    op.create_index('ix_incidents_occurred_at', 'incidents', ['occurred_at'], unique=False)
    op.create_index('ix_incidents_severity', 'incidents', ['severity'], unique=False)
    op.create_index('ix_incidents_zone', 'incidents', ['zone'], unique=False)
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.String(length=50), nullable=False, comment='Equipment reference code'),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('maintenance_type', sa.Enum('PREVENTIVE', 'CORRECTIVE', name='maintenancetype', native_enum=False, length=20), nullable=False),
    sa.Column('assigned_team', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'ONGOING', 'COMPLETED', name='maintenancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenance_logs_created_at', 'maintenance_logs', ['created_at'], unique=False)
    op.create_index('ix_maintenance_logs_equipment_id', 'maintenance_logs', ['equipment_id'], unique=False)
    op.create_index('ix_maintenance_logs_maintenance_type', 'maintenance_logs', ['maintenance_type'], unique=False)
    op.create_index('ix_maintenance_logs_status', 'maintenance_logs', ['status'], unique=False)
    op.create_table('permits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('permit_type', sa.Enum('HOT_WORK', 'CONFINED_SPACE', 'ELECTRICAL', name='permittype', native_enum=False, length=30), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('issued_by', sa.String(length=100), nullable=False, comment='Safety officer who issued the permit'),
    sa.Column('assigned_team', sa.String(length=100), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Permit expiry time'),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'SUSPENDED', name='permitstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permits_end_time', 'permits', ['end_time'], unique=False)
    op.create_index('ix_permits_permit_type', 'permits', ['permit_type'], unique=False)
    op.create_index('ix_permits_status', 'permits', ['status'], unique=False)
    op.create_index('ix_permits_zone', 'permits', ['zone'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False, comment='Compound risk score between 0.0 and 100.0'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=20), nullable=False),
    sa.Column('contributing_factors', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_scores_analyzed_at', 'risk_scores', ['analyzed_at'], unique=False)
    op.create_index('ix_risk_scores_risk_level', 'risk_scores', ['risk_level'], unique=False)
    op.create_index('ix_risk_scores_zone', 'risk_scores', ['zone'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('zone', sa.String(length=50), nullable=False, comment='Plant zone identifier'),
    sa.Column('sensor_type', sa.Enum('GAS', 'TEMPERATURE', 'PRESSURE', 'HUMIDITY', name='sensortype', native_enum=False, length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=False, comment='Sensor reading value'),
    sa.Column('unit', sa.String(length=20), nullable=False, comment='Measurement unit (e.g. °C, ppm, bar)'),
    sa.Column('status', sa.Enum('NORMAL', 'WARNING', 'CRITICAL', name='sensorstatus', native_enum=False, length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensors_sensor_type', 'sensors', ['sensor_type'], unique=False)
    op.create_index('ix_sensors_status', 'sensors', ['status'], unique=False)
    op.create_index('ix_sensors_zone_timestamp', 'sensors', ['zone', 'timestamp'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique worker identifier (UUID v4)'),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False, comment='Employee badge number'),
    sa.Column('department', sa.String(length=100), nullable=False, comment='Organisational department'),
    sa.Column('role', sa.String(length=100), nullable=False, comment='Job title / role'),
    sa.Column('current_zone', sa.String(length=50), nullable=True, comment='Current plant zone'),
    sa.Column('ppe_status', sa.Boolean(), nullable=False, comment='True when PPE-compliant'),
    sa.Column('shift', sa.String(length=20), nullable=False, comment='Morning / Afternoon / Night'),
    sa.Column('status', sa.Enum('WORKING', 'IDLE', 'EMERGENCY', name='workerstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index('ix_workers_current_zone', 'workers', ['current_zone'], unique=False)
    op.create_index('ix_workers_department', 'workers', ['department'], unique=False)
    op.create_index('ix_workers_status', 'workers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workers_status', table_name='workers')
    op.drop_index('ix_workers_department', table_name='workers')
    op.drop_index('ix_workers_current_zone', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_sensors_zone_timestamp', table_name='sensors')
    op.drop_index('ix_sensors_status', table_name='sensors')
    op.drop_index('ix_sensors_sensor_type', table_name='sensors')
    op.drop_table('sensors')
    op.drop_index('ix_risk_scores_zone', table_name='risk_scores')
    op.drop_index('ix_risk_scores_risk_level', table_name='risk_scores')
    op.drop_index('ix_risk_scores_analyzed_at', table_name='risk_scores')
    op.drop_table('risk_scores')
    op.drop_index('ix_permits_zone', table_name='permits')
    op.drop_index('ix_permits_status', table_name='permits')
    op.drop_index('ix_permits_permit_type', table_name='permits')
    op.drop_index('ix_permits_end_time', table_name='permits')
    op.drop_table('permits')
    op.drop_index('ix_maintenance_logs_status', table_name='maintenance_logs')
    op.drop_index('ix_maintenance_logs_maintenance_type', table_name='maintenance_logs')
    op.drop_index('ix_maintenance_logs_equipment_id', table_name='maintenance_logs')
    op.drop_index('ix_maintenance_logs_created_at', table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_index('ix_incidents_zone', table_name='incidents')
    op.drop_index('ix_incidents_severity', table_name='incidents')
    op.drop_index('ix_incidents_occurred_at', table_name='incidents')
    op.drop_index('ix_incidents_incident_type', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_alerts_zone', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_generated_at', table_name='alerts')
    op.drop_index('ix_alerts_alert_type', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
