"""update_enum_constraints

Revision ID: fe013d997172
Revises: 626fd0bf74ec
Create Date: 2026-07-21 17:56:42.945664
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe013d997172'
down_revision: Union[str, None] = '626fd0bf74ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # Drop existing constraints
    op.execute("ALTER TABLE sensors DROP CONSTRAINT IF EXISTS sensortype;")
    op.execute("ALTER TABLE incidents DROP CONSTRAINT IF EXISTS incidenttype;")
    
    # Update existing data to lowercase
    op.execute("UPDATE sensors SET sensor_type = LOWER(sensor_type);")
    op.execute("UPDATE incidents SET incident_type = LOWER(incident_type);")
    
    # Recreate constraints with lowercase values matching the updated Enums
    op.execute("ALTER TABLE sensors ADD CONSTRAINT sensortype CHECK (sensor_type IN ('gas', 'temperature', 'pressure', 'humidity', 'smoke'));")
    op.execute("ALTER TABLE incidents ADD CONSTRAINT incidenttype CHECK (incident_type IN ('gas_leak', 'fire', 'explosion', 'ppe_violation', 'emergency_response', 'worker_collapse'));")


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
