"""Add user settings fields

Revision ID: 626fd0bf74ec
Revises: a1b2c3d4e5f6
Create Date: 2026-07-21 17:48:02.453644
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '626fd0bf74ec'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               comment='Alert severity assigned by the rule that generated it',
               existing_nullable=False)
    op.alter_column('alerts', 'source',
               existing_type=sa.VARCHAR(length=30),
               server_default=None,
               comment='Monitoring subsystem that produced the triggering data',
               existing_nullable=False)
    op.alter_column('document_embeddings', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_comment='Full chunk metadata, preserved as-is',
               existing_nullable=False)
    op.alter_column('timeline_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment="Severity classified at ingestion time from the event's source/type/payload",
               existing_nullable=False)
    op.alter_column('timeline_events', 'ai_decision_reference',
               existing_type=sa.VARCHAR(length=200),
               comment="Free-form reference to the AI decision this event is linked to (e.g. a recommendation's source+zone+reason, or an explainability summary id). No decisions table exists yet — this column stores whatever identifier the publisher supplies.",
               existing_comment='Free-form reference to the AI decision this event is linked to, if any',
               existing_nullable=True)
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('employee_id', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment='Unique user identifier (UUID v4)',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'viewer'::character varying"),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique user identifier (UUID v4)',
               existing_nullable=False)
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'employee_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'department')
    op.alter_column('timeline_events', 'ai_decision_reference',
               existing_type=sa.VARCHAR(length=200),
               comment='Free-form reference to the AI decision this event is linked to, if any',
               existing_comment="Free-form reference to the AI decision this event is linked to (e.g. a recommendation's source+zone+reason, or an explainability summary id). No decisions table exists yet — this column stores whatever identifier the publisher supplies.",
               existing_nullable=True)
    op.alter_column('timeline_events', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'low'::character varying"),
               existing_comment="Severity classified at ingestion time from the event's source/type/payload",
               existing_nullable=False)
    op.alter_column('document_embeddings', 'chunk_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_comment='Full chunk metadata, preserved as-is',
               existing_nullable=False)
    op.alter_column('alerts', 'source',
               existing_type=sa.VARCHAR(length=30),
               server_default=sa.text("'SENSOR_MONITORING'::character varying"),
               comment=None,
               existing_comment='Monitoring subsystem that produced the triggering data',
               existing_nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'MEDIUM'::character varying"),
               comment=None,
               existing_comment='Alert severity assigned by the rule that generated it',
               existing_nullable=False)
    # ### end Alembic commands ###
